% Script generated by Brainstorm (04-Mar-2024)

% Input files
sFiles = bst_process('CallProcess', 'process_select_search', [], [], ...
    'search', '(([parent CONTAINS "simul |"] AND [parent CONTAINS "0.25db"]))');

[~,index] = sortrows({sFiles.DataFile}.'); sFiles = sFiles(index(end:-1:1)); clear index

RawFiles = {'/Users/edelaire1/Documents/Project/wMEM-fnirs/data/metrics/metrics_simul_0.25db_new.txt'};

% Start a new report
bst_report('Start', sFiles);
n_files = length(sFiles)/3;

for iSimul = 1:3:(length(sFiles)-1)
    idx_file  = [iSimul, iSimul+1, iSimul+2];
    
    bst_process('CallProcess', 'process_nst_wMEM_metrics', sFiles(idx_file), [], ...
        'maxDist',  40, ...
        'textFile', {RawFiles{1}, 'txt'});

end

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);
% bst_report('Email', ReportFile, username, to, subject, isFullReport);

% Delete temporary files
% gui_brainstorm('EmptyTempFolder');

