
SNR = -1;

sFiles = bst_process('CallProcess', 'process_select_search', [], [], ...
    'search', [ '(( [name CONTAINS "Avg: Task"] ', ....
                'AND', ....
                sprintf('[parent EQUALS "simulation_wake_task_%0.2fdB_left_medium"]',SNR), ...
                '))' ] ...
                );


bst_report('Start', sFiles);


output_path = "/Users/edelaire1/Documents/Project/wMEM-fnirs/data/metrics/metrics_task";

MetricFile = { ...
                sprintf('metrics_cMEM_simul-task_%0.2fdB_medium.csv', SNR) ;...
                sprintf('metrics_wMEM_simul-task_%0.2fdB_medium.csv', SNR) ;...
                sprintf('metrics_MNE_simul-task_%0.2fdB_medium.csv', SNR ) ; ...
              };

for iFile = 1:length(sFiles)

    % Get results files 
    [sStudy, iStudy, iResults] = bst_get('ResultsForDataFile', sFiles(iFile).FileName);
    ResultFiles = sStudy.Result(iResults);
    

    % Process: Compute statistics on cMEM
    sMaps = ResultFiles( contains({ResultFiles.Comment}, {'Ground Truth', 'cMEM'}));
    bst_process('CallProcess', 'process_nst_wMEM_metrics', {sMaps.FileName}, [], ...
                                                'time_of_interest',  10, ...
                                                'range_of_interest', [0, 20], ...
                                               'textFile', {fullfile(output_path, MetricFile{1}), 'csv'});

    % Process: Compute statistics on wMEM
    sMaps = ResultFiles( contains({ResultFiles.Comment}, {'Ground Truth', 'wMEM'}));
    bst_process('CallProcess', 'process_nst_wMEM_metrics', {sMaps.FileName}, [], ...
                                                'time_of_interest',  10, ...
                                                'range_of_interest', [0, 20], ...
                                               'textFile', {fullfile(output_path, MetricFile{2}), 'csv'});

        % Process: Compute statistics on MNE
    sMaps = ResultFiles( contains({ResultFiles.Comment}, {'Ground Truth', 'MNE'}));
    bst_process('CallProcess', 'process_nst_wMEM_metrics', {sMaps.FileName}, [], ...
                                                'time_of_interest',  10, ...
                                                'range_of_interest', [0, 20], ...
                                               'textFile', {fullfile(output_path, MetricFile{3}), 'csv'});
end


% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);