sFiles = {...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1911.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1913.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1915.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1917.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1919.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1921.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1923.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1925.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1927.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1929.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1931.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1933.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1935.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1937.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1939.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1941.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1943.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1945.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1947.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1949.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1951.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1953.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1955.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1957.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1959.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1961.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1963.mat', ...
    'sub-02/simulation_wake_osc_-1.00dB_left_medium/data_sim_250420_1965.mat'};

timewindow_full      = [5, 340];
baselinewindow_full  = [50, 100];

% Start a new report
bst_report('Start', sFiles);

parpool(2);

for iFile = 1:length(sFiles)

    sInput = sFiles{iFile};


    % Process: Source reconstruction - wMNE
    bst_process('CallProcess', 'process_nst_wmne', sInput, [], ...
                                                'thresh_dis2cortex',  5, ...
                                                'depth_weightingMNE', 0.3, ...
                                                'TimeSegment',        timewindow_full, ...
                                                'NoiseCov_recompute', 1, ...
                                                'TimeSegmentNoise',   baselinewindow_full);

    selected_scales = [1:8]; alpha_init = 7; neighborhood_order = 4; normalization = 'fixed';
    compute_wMEM(sInput, timewindow_full, baselinewindow_full, neighborhood_order, selected_scales, alpha_init, normalization);

    selected_scales = [1:8]; alpha_init = 7; neighborhood_order = 4; normalization = 'adaptive';
    compute_wMEM(sInput, timewindow_full, baselinewindow_full, neighborhood_order, selected_scales, alpha_init, normalization);
end

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);


function sFilesMEM = compute_wMEM(sImput, timewindow_full, baselinewindow_full, neighborhood_order, selected_scales, alpha_init, normalization)

    mem_option = be_pipelineoptions([], 'wMEM','NIRS');
    mem_option.optional = struct_copy_fields(mem_option.optional, ...
                                        struct(...
                                        'TimeSegment',    timewindow_full, ...
                                        'BaselineType',    {{'within-data'}}, ...
                                        'BaselineHistory', {{'within'}}, ...
                                        "baseline_shuffle", 0, ...
                                        "BaselineSegment", baselinewindow_full , ...
                                        'display',         0));
    
    mem_option.clustering =  struct_copy_fields(mem_option.clustering, ...
                                         struct('neighborhood_order', neighborhood_order));
    
    mem_option.wavelet.selected_scales  = selected_scales;
    mem_option.model.alpha_method       = alpha_init;
    mem_option.optional.normalization   = normalization;
    mem_option.solver.parallel_matlab   = 1;
    
    sFilesMEM = bst_process('CallProcess', 'process_nst_cmem', sImput, [], ...
        'mem', struct('MEMpaneloptions', mem_option), ...
        'thresh_dis2cortex',       5, ...
        'NoiseCov_recompute',      1, ...
        'auto_neighborhood_order', 0, ...
        'store_sparse_results',    0);
    
    sFilesMEM =  bst_process('CallProcess', 'process_add_tag', sFilesMEM, [], ...
        'tag',            sprintf('| nbo = %d | alpha = %d | norm = %s',  neighborhood_order, alpha_init, normalization), ...
        'output',         'name'); 

end